import type { AppState } from "./types";
import { uid } from "./lib";

const now = Date.now();

export const seed: AppState = {
  boards: ["Design", "Edit", "Code", "Life"],
  blockedSecrets: 0,
  lastBlockedAt: null,
  layout: "horizontal",
  notesByDay: {
    [new Date().toISOString().slice(0, 10)]:
      "Ship Cove as one notch, not two apps.\nKeep clipboard types visible without folders.\nTurn copied error text into a task when it matters.\nAsk Arpit/Aditya-shaped question: what belongs in the island when idle?",
  },
  events: [
    { id: "e1", title: "Design critique", start: "14:30", end: "15:00", calendar: "Work" },
    { id: "e2", title: "Walk + errands", start: "17:45", end: "18:30", calendar: "Personal" },
    { id: "e3", title: "Write release note", start: "20:00", end: "20:40", calendar: "Work" },
  ],
  tasks: [
    { id: "t1", title: "Polish the notch expand so it feels like the island, not a window", done: false, createdAt: now - 3600_000 },
    { id: "t2", title: "Auto-sort colors, links, and code without asking", done: false, createdAt: now - 7200_000 },
    { id: "t3", title: "Block secrets before they ever hit history", done: true, createdAt: now - 10800_000, doneAt: now - 9000_000 },
  ],
  focusLog: [
    { id: "f1", mode: "pomodoro", startedAt: now - 86400000 * 1 - 3600_000, durationMs: 25 * 60 * 1000, taskId: "t3" },
    { id: "f2", mode: "deep", startedAt: now - 7200_000, durationMs: 48 * 60 * 1000, taskId: "t1" },
    { id: "f3", mode: "pomodoro", startedAt: now - 3600_000, durationMs: 12 * 60 * 1000, taskId: "t2" },
  ],
  focus: {
    running: false,
    mode: "pomodoro",
    remainingMs: 25 * 60 * 1000,
    durationMs: 25 * 60 * 1000,
    taskId: "t1",
    startedAt: null,
  },
  clips: [
    {
      id: uid("clip"),
      kind: "color",
      content: "#6C6CF8",
      preview: "#6C6CF8",
      createdAt: now - 40_000,
      pinned: true,
      board: "Design",
      source: "Figma",
      meta: { colorName: "Iris" },
    },
    {
      id: uid("clip"),
      kind: "token",
      content: "--iris: #6C6CF8",
      preview: "--iris: #6C6CF8",
      createdAt: now - 55_000,
      pinned: false,
      board: "Design",
      source: "Figma",
      meta: { tokenName: "--iris", colorName: "Iris" },
    },
    {
      id: uid("clip"),
      kind: "svg",
      content: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="14" fill="#6C6CF8"/><circle cx="32" cy="32" r="14" fill="#C9A870"/></svg>`,
      preview: "SVG",
      createdAt: now - 80_000,
      pinned: false,
      board: "Design",
      source: "Figma",
      meta: { language: "SVG", width: 64, height: 64 },
    },
    {
      id: uid("clip"),
      kind: "audio",
      content: "Ship Cove as one notch, not two apps.",
      preview: "Ship Cove as one notch, not two apps.",
      createdAt: now - 20_000,
      pinned: false,
      board: "Edit",
      source: "Roux",
      meta: {
        durationMs: 7400,
        transcript: "Ship Cove as one notch, not two apps.",
        peaks: [0.12, 0.4, 0.7, 0.55, 0.3, 0.62, 0.8, 0.45, 0.2, 0.5, 0.66, 0.3, 0.18, 0.42, 0.7, 0.38],
      },
    },
    {
      id: uid("clip"),
      kind: "timecode",
      content: "01:12:08:12",
      preview: "01:12:08:12",
      createdAt: now - 200_000,
      pinned: false,
      board: "Edit",
      source: "Premiere",
      meta: { seconds: 4328 },
    },
    {
      id: uid("clip"),
      kind: "path",
      content: "/Volumes/Media/A-roll-take-03.mov",
      preview: "A-roll-take-03.mov",
      createdAt: now - 260_000,
      pinned: false,
      board: "Edit",
      source: "Finder",
      meta: { pathName: "A-roll-take-03.mov", fileName: "A-roll-take-03.mov" },
    },
    {
      id: uid("clip"),
      kind: "code",
      content: `func capturePasteboard(_ changeCount: Int) {\n    guard changeCount != lastCount else { return }\n    lastCount = changeCount\n    classify(NSPasteboard.general)\n}`,
      preview: "func capturePasteboard(_ changeCount: Int)",
      createdAt: now - 480_000,
      pinned: false,
      board: "Code",
      source: "Xcode",
      meta: { language: "Swift" },
    },
    {
      id: uid("clip"),
      kind: "link",
      content: "https://www.figma.com/design/cove/island",
      preview: "figma.com/design/cove/island",
      createdAt: now - 120_000,
      pinned: false,
      board: "Design",
      source: "Safari",
      meta: { domain: "figma.com" },
    },
    {
      id: uid("clip"),
      kind: "text",
      content: "gowtham@altcarbon.com",
      preview: "gowtham@altcarbon.com",
      createdAt: now - 900_000,
      pinned: false,
      board: "Life",
      source: "Mail",
      meta: {},
    },
    {
      id: uid("clip"),
      kind: "image",
      content: "linear-gradient(135deg,#2a2438,#6a4a38 42%,#c9a870)",
      preview: "Screenshot",
      createdAt: now - 1800_000,
      pinned: false,
      board: "Life",
      source: "Screenshot",
      meta: {
        ocr: "Cove  24:12  Brand review\nKeep this in the island while you work.",
        width: 1440,
        height: 900,
      },
    },
    {
      id: uid("clip"),
      kind: "link",
      content: "https://www.notchowl.com/",
      preview: "www.notchowl.com/",
      createdAt: now - 3600_000,
      pinned: false,
      board: "Life",
      source: "Safari",
      meta: { domain: "notchowl.com" },
    },
    {
      id: uid("clip"),
      kind: "color",
      content: "#C9A870",
      preview: "#C9A870",
      createdAt: now - 5400_000,
      pinned: false,
      board: "Design",
      source: "Figma",
      meta: { colorName: "Brass" },
    },
  ],
};

